publicity_user:
    resource: "@PublicityUserBundle/Resources/config/routing.yml"
    prefix:   /

class_user:
    resource: "@ClassUserBundle/Resources/config/routing.yml"
    prefix:   /class/

user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /

fos_user_changePassword:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /reg/
    
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset/