security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_TEACHER:     ROLE_TEACHER
        ROLE_STUDENT:     ROLE_STUDENT
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                always_use_default_target_path: false
                default_target_path:            /class/profile/selection
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/class/profile/student/  , role: IS_AUTHENTICATED_FULLY }
        - { path: ^/class/profile/teacher/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/superAdmin/, role: ROLE_SUPER_ADMIN }