Sasip\ClassUserBundle\Entity\Exams:
    type: entity
    table: exam
    
    id:
        id:
            type: string
            length: 6

    fields:
        fee:
            type: integer
        conductDay:
            type: string
            length: 15
        time:
            type: string
            length: 15
        teacher_id:
            type: string
            length: 6
        