Sasip\ClassUserBundle\Entity\Message:
    type: entity
    table: send_messages
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    
    fields:
        student_id:
            type: string
            length: 255
        state:
            type: string
            length: 7
        teacher_id:
            type: string
            length: 255
        content:
            type: text
        sender:
            type: string
            length: 255
        time_sent:
            type: string
            length: 12
        title:
            type: text
        date_sent:
            type: string
            length: 12
        
        