Sasip\ClassUserBundle\Entity\Message:
    type: entity
    table: messages
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    
    fields:        
        state:
            type: string
            length: 7        
        content:
            type: text
        sender:
            type: string
            length: 255
        receiver:
            type: string
            length: 255
        time_sent:
            type: time
            length: 12
        title:
            type: text
        date_sent:
            type: date
            length: 12
        
        