Sasip\ClassUserBundle\Entity\Mobile:
    type: entity
    table: contact_numbers
    
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
                
    fields:
        personId:
            type: string
            length: 255
            
        contactNumber:
            type: string
            length: 12