## YAML Template.
Sasip\ClassUserBundle\Entity\Student:
    type: entity
    table: student
    
    id:
        id:
            type: string
            length: 6
            
    fields:
        firstName:
            type: text
        lastName:
            type: text
        year_Of_exam:
            type: integer
            length: 5
        address:
            type: text
        school:
            type: text
        parent_mobile:
            type: string
            length: 10
        parent_name:
            type: text