Sasip\ClassUserBundle\Entity\TutionClass:
    type: entity
    table: class
    
    id:
        id:
            type: string
            length: 6
            
    fields:
        fees:
            type: text
        conductDay:
            type: string
            length: 15
        time:
            type: string
            length: 12
        teacher_id:
            type: text
        subject:
            type: text
            