#------------------------User Profiles-------------------------
Profile_user:
    path:     /profile/user
    defaults: { _controller: ClassUserBundle:Role:user }
Profile_teacher:
    path:     /profile/teacher
    defaults: { _controller: ClassUserBundle:Role:teacher }
Profile_student:
    path:     /profile/student/{student_id}
    defaults: { _controller: ClassUserBundle:Role:student }
Profile_superAdmin:
    path:     /profile/superAdmin
    defaults: { _controller: ClassUserBundle:Role:superAdmin }
    
    
#    --------------------Profile Selector-----------------------------------
Profile_selector:
    path:     /profile/selection
    defaults: { _controller: ClassUserBundle:Role:roleSelect }
    
#    --------------------------test-----------------------------
    
test:
    path:   /test
    defaults: {_controller: ClassUserBundle:Default:index}
    
    
#-------------------------------StudentProfileActions-------------------------

studentAttendanceClass:
    path:   /studentClassAttendance
    defaults: {_controller: ClassUserBundle:AttendanceAnalyzer:studentClassAttendance}

studentAttendanceExam:
    path:   /studentExamAttendance
    defaults: {_controller: ClassUserBundle:AttendanceAnalyzer:studentAttendanceExam}

studentViewAllResults:
    path:   /studentViewAllResults/{examId}
    defaults: {_controller: ClassUserBundle:ResultAnalyze:individualResult}
    
studentAnalysisTemplateResults:
    path:   /studentAnalysisTemplateResults/
    defaults: {_controller: ClassUserBundle:ResultAnalyze:resultAnalysisTemplate}    

studentProfileSettings:
    path:   /studentProfileSettings/
    defaults: {_controller: ClassUserBundle:Settings:studentProfile} 
    
studentFormData:
    path:   /formData/
    defaults: {_controller: ClassUserBundle:Settings:sendData} 

studentFormUpdate:
    path:   /formUpdateData/
    defaults: {_controller: ClassUserBundle:Settings:studentUpdateProfile} 

#--------------------------------routes for utilities---------------------------------------------------

studentIndividualResultComponenent:
    path:   /studentResultComponent/
    defaults: {_controller: ClassUserBundle:ResultAnalyze:getResultIndividualComponent}

studentAnalysisResults:
    path:   /studentAnalysisResults/
    defaults: {_controller: ClassUserBundle:ResultAnalyze:resultAnalysis}   
#-------------------------------------------------------------------------------------------------------


#--------------------------------routes for news forum--------------------------------------------------

displayForum:
    path:   /displayForum/
    defaults: {_controller: ClassUserBundle:NewsForum:displayForum}

sendMessage:
    path:   /sendMesasge/
    defaults: {_controller: ClassUserBundle:NewsForum:sendMsg}

viewMoreMessage:
    path:   /viewMore/
    defaults: {_controller: ClassUserBundle:NewsForum:viewMore}

#--------------------------------end routes for news forum----------------------------------------------



#--------------------------------Class Configuration----------------------------------------------
classConfiguration:
    path:   /classConfig/
    defaults: {_controller: ClassUserBundle:ClassConfiguration:classConfig}

classUpdate:
    path:   /classUpdate/
    defaults: {_controller: ClassUserBundle:ClassConfiguration:update}
    
ExamConfiguration:
    path:   /examConfig/
    defaults: {_controller: ClassUserBundle:ExamConfig:examConfig}

ExamUpdate:
    path:   /examUpdate/
    defaults: {_controller: ClassUserBundle:ExamConfig:update}


#--------------------------------end routes for Class Configuration-------------------------------