studentAccountSettings:
    path:   /studentAccountSettings/
    defaults: {_controller: UserBundle:Settings:displayStudentProfile}
    
superAdminCreateProfiles:
    path:   /createProfiles/
    defaults: {_controller: UserBundle:Registration:register}
